# Generated by Django 5.2.8 on 2025-12-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='is_destination',
            field=models.BooleanField(default=False),
        ),
    ]
